services:
  logs-monitoring:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid  && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/estagioSRE
      - ~/:/estagioSRE/output_data/
    user: "1001:1001"
    ports:
      - "3000:3000"
      - "1235:12345"
  prometheus:
    image: prom/prometheus:v2.33.1
    ports:
      - "9090:9090"
    user: "1001:1001"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
  generate-logs:
    image: ghcr.io/toledompm/log-gen:latest
    volumes:
      - ./log_storage:/tmp