services:
  logs-monitoring:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid  && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/estagioSRE
      - ~/:/estagioSRE/output_data/
    user: "1001:1001"
    ports:
      - "3000:3000"